export { default as DashboardHome } from "./Dashboard/Home"
export { default as DashboardRewards } from "./Dashboard/Rewards"
export { default as DashboardWallet } from "./Dashboard/Wallet"
export { default as DashboardExchange } from "./Dashboard/Exchange"
export { default as DashboardMembership } from "./Dashboard/Membership"
export { default as DashboardSocial } from "./Dashboard/Social"
export { default as DashboardGuilds } from "./Dashboard/Guilds"
export { default as DashboardLeaderboard } from "./Dashboard/Leaderboard"